using System.Text;
using System.Text.Json;
using System.Xml;
using AstroForge.Core.IO;
using AstroForge.Core.Export;
using AstroForge.Core.Models;

namespace AstroForge.Core.Wbpp;

public static class WbppInstanceGenerator
{
    public static string Generate(ProjectPlan plan)
    {
        if (!Directory.Exists(plan.ProjectRoot))
            throw new DirectoryNotFoundException("Esporta prima il progetto: l’istanza WBPP usa i percorsi della cartella finale.");
        plan = ResolveExportedFiles(plan);
        if (!plan.Files.Any(file => file.Role == "light"))
            throw new InvalidOperationException("Il progetto esportato non contiene Light da caricare in WBPP.");

        var output = string.IsNullOrWhiteSpace(plan.PixInsightOutputFolderName)
            ? Path.Combine(plan.ProjectRoot, "PixInsight Output")
            : Path.Combine(plan.ProjectRoot, plan.PixInsightOutputFolderName);
        Directory.CreateDirectory(output);

        var preGroups = plan.Files.Where(file => file.Role != "excluded-light")
            .GroupBy(GroupKey)
            .Select((items, index) => CreateGroup(items.ToArray(), index + 1, plan, 1));
        // WBPP reconstructs its POST groups from PRE groups with its own rules.
        var groups = preGroups.ToArray();
        var keywords = plan.Recipe.Keywords.Select(item => new { name = item.Keyword, mode = (item.Pre ? 1 : 0) | (item.Post ? 2 : 0) }).ToArray();
        var parameters = new Dictionary<string, string>
        {
            ["VERSION"] = "3.0.1",
            ["DATA_VERSION"] = "1",
            ["PRODUCT"] = "WBPP",
            ["saveFrameGroups"] = "true",
            ["smartNamingOverride"] = "true",
            ["detectMasterIncludingFullPath"] = "true",
            ["referenceImage"] = "",
            ["reuseLastReferenceFrames"] = "false",
            ["imageRegistration"] = "true",
            ["integrate"] = "true",
            ["groupingKeywordsEnabled"] = keywords.Length > 0 ? "true" : "false",
            ["outputDirectory"] = Encode(PathForPixInsight(output)),
            ["usePipelineScript"] = "false",
            ["enableCompactGUI"] = "false",
            ["keywords"] = Encode(JsonSerializer.Serialize(keywords)),
            ["groups"] = Encode(JsonSerializer.Serialize(groups)),
            ["cache_v2"] = Encode("{}")
        };

        var settings = new XmlWriterSettings { Indent = true, Encoding = new UTF8Encoding(false), OmitXmlDeclaration = false };
        var path = Path.Combine(plan.ProjectRoot, $"{plan.ProjectName}-WBPP.xpsm");
        using var writer = XmlWriter.Create(path, settings);
        writer.WriteStartDocument();
        writer.WriteStartElement("xpsm", "http://www.pixinsight.com/xpsm");
        writer.WriteAttributeString("version", "1.0");
        writer.WriteAttributeString("xmlns", "xsi", null, "http://www.w3.org/2001/XMLSchema-instance");
        writer.WriteAttributeString("xsi", "schemaLocation", null, "http://www.pixinsight.com/xpsm http://pixinsight.com/xpsm/xpsm-1.0.xsd");
        writer.WriteStartElement("instance");
        writer.WriteAttributeString("class", "Script"); writer.WriteAttributeString("version", "256"); writer.WriteAttributeString("id", "AstroForge_WBPP");
        Element(writer, "parameter", "$PXI_SRCDIR/scripts/BatchPreprocessing/WBPP.js", "filePath");
        // Script checksums describe PixInsight's compiled script, not the raw JS file.
        // An empty checksum lets PixInsight compile its own installed WBPP version.
        Element(writer, "parameter", "", "md5sum");
        writer.WriteStartElement("table"); writer.WriteAttributeString("id", "parameters"); writer.WriteAttributeString("rows", parameters.Count.ToString());
        foreach (var pair in parameters)
        {
            writer.WriteStartElement("tr"); Element(writer, "td", pair.Key, "id"); Element(writer, "td", pair.Value, "value"); writer.WriteEndElement();
        }
        writer.WriteEndElement();
        Element(writer, "parameter", "", "information");
        writer.WriteEndElement();
        writer.WriteStartElement("icon");
        writer.WriteAttributeString("id", "AstroForge_WBPP");
        writer.WriteAttributeString("instance", "AstroForge_WBPP");
        writer.WriteAttributeString("xpos", "80");
        writer.WriteAttributeString("ypos", "80");
        writer.WriteAttributeString("workspace", "Workspace01");
        writer.WriteEndElement(); writer.WriteEndElement(); writer.WriteEndDocument();
        writer.Flush();
        // Include the installed WBPP entry point in the same runtime: Script
        // instances cannot execute recursively from another PixInsight script.
        File.WriteAllText(LauncherPath(path),
            "#engine v8\n// Generated by AstroProject Forge. Opens WBPP without starting image processing.\n" +
            "Parameters.clear();\n" +
            string.Join("\n", parameters.Select(pair => "Parameters.set(" + JsonSerializer.Serialize(pair.Key) + ", " + JsonSerializer.Serialize(pair.Value) + ");")) +
            "\n#include <../src/scripts/BatchPreprocessing/WBPP.js>\n", new UTF8Encoding(false));
        return path;
    }

    public static string LauncherPath(string instancePath) => Path.ChangeExtension(instancePath, ".js");

    private static object CreateGroup(PlannedFile[] files, int counter, ProjectPlan plan, int mode)
    {
        var first = files[0]; var frame = first.Frame; var type = ImageType(first.Role);
        var keywords = Keywords(first, plan).Where(pair => plan.Recipe.Keywords.Any(k => k.Keyword == pair.Key && k.Pre)).ToDictionary(pair => pair.Key, pair => pair.Value);
        var exposure = type == 1 ? 0 : frame.ExposureSeconds.Value ?? 0;
        var binning = frame.XBin.Value ?? 1;
        var width = frame.Width.Value ?? 0; var height = frame.Height.Value ?? 0;
        var cfa = !string.IsNullOrWhiteSpace(frame.BayerPattern.Value);
        var filter = type is 1 or 2 ? "" : frame.FilterName.Value ?? "";
        var items = files.Select(file => CreateItem(file, plan)).ToArray();
        return new
        {
            imageType = type, binning, hasMaster = files.Any(file => file.Frame.IsMaster), exposureTime = exposure, filter,
            exposureTimes = files.Select(file => file.Frame.ExposureSeconds.Value ?? 0).Distinct().ToArray(), optimizeMasterDark = false,
            size = new { width, height }, isCFA = cfa, CFAPattern = 0, debayerMethod = 2, keywords, mode,
            fileItems = items, lightOutputPedestalMode = 1, lightOutputPedestal = 0, lightOutputPedestalLimit = 0.0001,
            drizzleData = new { enabled = false, fast = true, scale = 1, dropShrink = 1, function = 0, gridSize = 16 },
            fastIntegration = new { }, frameFilterConfig = (object?)null, isHidden = false, isActive = true,
            footerLengthForCurrentHeader = 0, forceNoDark = false, forceNoFlat = false,
            id = FormattableString.Invariant($"{type}_{binning}_{filter}_{exposure}_{(cfa ? "CFA" : "mono")}_{string.Join('_', keywords.Select(pair => $"{pair.Key}:{pair.Value}"))}_{mode}_none_{width}x{height}"),
            fastIntegrationData = new { enabled = false, manuallyChanged = false, saveRegisteredImages = false, weightingScheme = 0 },
            ccData = new { enabled = true, highSigma = 10, CCTemplate = "" }, __counter__ = counter
        };
    }

    private static object CreateItem(PlannedFile file, ProjectPlan plan)
    {
        var frame = file.Frame; var path = PathForPixInsight(Path.Combine(plan.ProjectRoot, file.RelativePath));
        var keywords = Keywords(file, plan); var type = ImageType(file.Role); var binning = frame.XBin.Value ?? 1;
        var width = frame.Width.Value ?? 0; var height = frame.Height.Value ?? 0; var cfa = !string.IsNullOrWhiteSpace(frame.BayerPattern.Value);
        var fileKeywords = new Dictionary<string, string>
        {
            ["IMAGETYP"] = frame.Kind.ToString().ToUpperInvariant(), ["EXPTIME"] = (frame.ExposureSeconds.Value ?? 0).ToString(System.Globalization.CultureInfo.InvariantCulture),
            ["XBINNING"] = binning.ToString(), ["YBINNING"] = (frame.YBin.Value ?? binning).ToString(), ["FILTER"] = frame.FilterName.Value ?? "",
            ["GAIN"] = (frame.Gain.Value ?? 0).ToString(System.Globalization.CultureInfo.InvariantCulture), ["OFFSET"] = (frame.Offset.Value ?? 0).ToString(System.Globalization.CultureInfo.InvariantCulture),
            ["INSTRUME"] = frame.Camera.Value ?? "", ["BAYERPAT"] = frame.BayerPattern.Value ?? ""
        };
        foreach (var pair in keywords) fileKeywords[pair.Key] = pair.Value;
        return new
        {
            filePath = path, imageType = type, binning, filter = frame.FilterName.Value ?? "", exposureTime = frame.ExposureSeconds.Value ?? 0,
            fileKeywords, enabled = true, size = new { width, height }, matchingSizes = new Dictionary<string, object>(),
            createdWithSmartNamingEnabled = true, solverParams = new { }, isCFA = cfa, isMaster = frame.IsMaster, keywords,
            overscan = new { enabled = false, overscan = Enumerable.Range(0, 4).Select(_ => new { enabled = false, sourceRect = EmptyRect(), targetRect = EmptyRect() }).ToArray(), imageRect = EmptyRect() },
            processed = new { }, current = new { @default = path }, descriptor = new { }, localNormalizationFile = new { }, drizzleFile = new { },
            isReference = new { @default = false }, __fastIntegration = 0
        };
    }

    private static Dictionary<string, string> Keywords(PlannedFile file, ProjectPlan plan)
    {
        var result = new Dictionary<string, string>();
        foreach (var recommendation in plan.Recipe.Keywords)
        {
            var key = recommendation.Keyword;
            var value = key switch
            {
                "FLATSET" => file.Role is "light" or "flat" ? Segment(file.RelativePath, "FLATSET_") ?? file.GroupId : null,
                "DARKSET" => Segment(file.RelativePath, "DARKSET_") ?? (file.Role == "dark" ? file.GroupId : null),
                "BIASSET" => Segment(file.RelativePath, "BIASSET_") ?? (file.Role == "bias" ? file.GroupId : null),
                "TARGET" => file.Role == "light" ? Segment(file.RelativePath, "TARGET_") ?? file.Frame.ObjectName.Value : null,
                _ => Segment(file.RelativePath, key + "_")
            };
            if (!string.IsNullOrWhiteSpace(value)) result[key] = value;
        }
        return result;
    }

    private static string GroupKey(PlannedFile file) => $"{ImageType(file.Role)}|{file.Frame.IsMaster}|{file.Frame.XBin.Value}|{file.Frame.ExposureSeconds.Value}|{file.Frame.FilterName.Value}|{file.Frame.Width.Value}x{file.Frame.Height.Value}|{file.GroupId}|{file.RelativePath.Split(Path.DirectorySeparatorChar).FirstOrDefault(part => part.StartsWith("DARKSET_", StringComparison.OrdinalIgnoreCase))}|{file.RelativePath.Split(Path.DirectorySeparatorChar).FirstOrDefault(part => part.StartsWith("BIASSET_", StringComparison.OrdinalIgnoreCase))}";
    private static int ImageType(string role) => role switch { "bias" => 1, "dark" => 2, "flat" => 3, _ => 4 };
    private static string? Segment(string relativePath, string prefix) => relativePath.Split(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar).FirstOrDefault(part => part.StartsWith(prefix, StringComparison.OrdinalIgnoreCase))?[prefix.Length..];
    private static string Encode(string value) => Convert.ToBase64String(Encoding.UTF8.GetBytes(value));
    private static object EmptyRect() => new { x0 = 0, y0 = 0, x1 = 0, y1 = 0, __className__ = "Rect" };

    private static ProjectPlan ResolveExportedFiles(ProjectPlan plan)
    {
        var exported = new Dictionary<string, string>(PathIdentity.Comparer);
        var manifest = Path.Combine(plan.ProjectRoot, "_AstroForge", "manifest.json");
        if (File.Exists(manifest))
        {
            using var document = JsonDocument.Parse(File.ReadAllText(manifest));
            foreach (var item in document.RootElement.GetProperty("files").EnumerateArray())
                exported[Path.GetFullPath(item.GetProperty("source").GetString()!)] = item.GetProperty("destination").GetString()!;
        }
        var root = Path.GetFullPath(plan.ProjectRoot) + Path.DirectorySeparatorChar;
        var files = plan.Files.Where(file => file.Role != "excluded-light").Select(file =>
        {
            var relative = exported.GetValueOrDefault(Path.GetFullPath(file.Frame.Path), file.RelativePath);
            var full = Path.GetFullPath(Path.Combine(root, relative));
            if (!full.StartsWith(root, OperatingSystem.IsWindows() ? StringComparison.OrdinalIgnoreCase : StringComparison.Ordinal))
                throw new InvalidDataException("Percorso WBPP esterno al progetto esportato.");
            if (!File.Exists(full)) throw new FileNotFoundException("Esporta le modifiche del progetto prima di creare l’istanza WBPP.", full);
            return file with { RelativePath = Path.GetRelativePath(root, full) };
        }).DistinctBy(file => file.RelativePath, PathIdentity.Comparer).ToArray();
        return plan with { Files = files };
    }
    private static string PathForPixInsight(string path) => Path.GetFullPath(path).Replace('\\', '/');
    private static void Element(XmlWriter writer, string name, string value, string id) { writer.WriteStartElement(name); writer.WriteAttributeString("id", id); writer.WriteString(value); writer.WriteEndElement(); }
}
